AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  zeitplanFuncion:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.8
      CodeUri: .
      Timeout: 10
      Events:
        zeitplanEquipoEliminar:
          Type: Api
          Properties:
            Path: /v1/equipos/{equipo_id}
            Method: delete
        zeitplanEquipoObtener:
          Type: Api
          Properties:
            Path: /v1/equipos/{equipo_id}
            Method: get
        zeitplanEquipoAgregar:
          Type: Api
          Properties:
            Path: /v1/equipos
            Method: post
        zeitplanUsuarioEliminar:
          Type: Api
          Properties:
            Path: /v1/usuario/{usuario_id}
            Method: delete
        zeitplanUsuarioObtener:
          Type: Api
          Properties:
            Path: /v1/usuario/{usuario_id}
            Method: get
        zeitplanUsuarioAgregar:
          Type: Api
          Properties:
            Path: /v1/usuario/
            Method: post
